### ISSUE TITLE
dypi_kastad, or some more specific descriptor

### ISSUE THREAD

**Issue by sigurdurthorjonsson** [einarhjorleifsson/ovog#6]
dypi_kastad, togdypi_kastad, botndypi_kastad hvað er í gildi nú?

Got an error on first trial of package 'ovog'

> zip_fileis <- c("A11-2024.zip","AMM4-2024.zip")
> 
> zip_file |>
+   hv_import_cruise() -> h
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `dypi_kastad` doesn't exist.

Note that ovog/R/global.R has, confusingly, both general and specific depths:

(base) sigurdur@Kerfisdeilds-MacBook-Pro R % grep -n dypi_kastad global.R 
3:  c("dags", "dags_byrjun", "dags_endir", "dypi_hift", "dypi_kastad", "fishing_gear_no",
10:    "aldur", "alls", "ar", "b.std", "botndypi_hift", "botndypi_kastad", "fisktegund_id",
23:    "tog_nr", "togdypi_hift", "togdypi_kastad", "togdypishiti", "togstefna", "unzip", "value

**Comment by einarhjorleifsson** [comment]
hmm, ... gætir þú sent mér skrárnar svo ég geti skoðað þetta frekar (er akkúrat að vinna í þessu tengt núna).

**Comment by einarhjorleifsson** [comment]
ahh, hurðu - held ég viti hvað er að - ætti ekki að vera með select skipun í hv_order föllunum. sendu mér samt skrárnar - gott að hafa þær sem test.

**Comment by einarhjorleifsson** [comment]
try: remotes::install_github("einarhjorleifsson/ovog@f17a69c286c08dcb98c78679b9fa38858a7d3fd3")
